# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

registries:
  coverlet-azure-devops:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/tonerdo/coverlet/_packaging/coverlet-nightly/nuget/v3/index.json

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 15
    registries:
      - coverlet-azure-devops
    labels:
      - "type: dependencies"
      - ".NET"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
