steps:
- task: UseDotNet@2
  inputs:
    version: 6.0.415
  displayName: Install .NET Core SDK 6.0.415

- task: UseDotNet@2
  inputs:
    version: 7.0.402
  displayName: Install .NET Core SDK 7.0.402

- script: dotnet pack -c Debug src/coverlet.msbuild.tasks/coverlet.msbuild.tasks.csproj
  displayName: Pack coverlet.msbuild

- script: dotnet pack -c Debug src/coverlet.collector/coverlet.collector.csproj
  displayName: Pack coverlet.collector

- script: dotnet restore
  displayName: Restore packages

- script: dotnet build -c $(BuildConfiguration) --no-restore -bl:build.binlog
  displayName: Build

- script: dotnet pack -c $(BuildConfiguration) --no-restore
  displayName: Pack

- task: DotNetCoreCLI@2
  displayName: Run tests with coverage
  inputs:
    command: test
    arguments: -c $(BuildConfiguration) -bl:test.binlog --no-build --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
    testRunTitle: $(Agent.JobName)

- template: publish-coverlet-result-files.yml

- template: publish-coverage-results.yml
  parameters:
    reports: $(Build.SourcesDirectory)/**/coverage.opencover.xml
    condition: and(succeeded(), eq(variables['BuildConfiguration'], 'Debug'))
    assemblyfilters: '-xunit;-coverlet.testsubject'

