name: "Publish coverage results"
description: ""uses reportgenerator task to create a code coverage report and aggregates available cobertura XML files. The results are publishes as a build artifact."

runs:
  using: "composite"  
  steps:
  - name: checkout repository
    uses: actions/checkout@v4

  - name: ReportGenerator
    uses: danielpalme/ReportGenerator-GitHub-Action@5.1.24
    with:
      reports: $GITHUB_WORKSPACE/**/coverage.opencover.xml
      assemblyfilters: -xunit*;+Coverlet.Core.*;+Coverlet.Collector.*
      targetdir: ./artifacts/CoverageReport
      reporttypes: HtmlInline;Cobertura;MarkdownSummaryGithub;lcov
      verbosity: Verbose

  - name: "Publish CoverageReport Artifact"
    uses: actions/upload-artifact@v3
    with:
      name: TestLogs_${{ matrix.os }})_${{ matrix.buildConfiguration }}
      path: ${{ github.workspace }}/artifacts/CoverageReport

  - name: Code Coverage Report
    uses: irongut/CodeCoverageSummary@v1.3.0
    with:
      filename: ${{ github.workspace }}/artifacts/CoverageReport/Cobertura.xml
      badge: true
      fail_below_min: true
      format: markdown
      hide_branch_rate: false
      hide_complexity: true
      indicators: true
      output: both
      thresholds: '60 80'

  - name: Add Coverage PR Comment
    uses: marocchino/sticky-pull-request-comment@v2
    if: github.event_name == 'pull_request'
    with:
      recreate: true
      path: code-coverage-results.md
